To plot the gamma 1D example, we need to know in which 10min window, there are most frequency picks. We can use the following code to find out.

In [1]:
import pandas as pd
from tqdm import tqdm

In [8]:
assignments=pd.read_csv("/Users/ziyixi/Library/CloudStorage/OneDrive-MichiganStateUniversity/Paper/PhaseNetTF_myturn/PhaseNet-TF-Figures/phasenettf/data/catalog/continious_associated_assignment.csv",skiprows=1,names=
                        ["id",	"date" ,"time"	,"amp"	,"type"	,"prob"	,"event_index"	,"gamma_score"],sep="\s+")
assignments["time"]=assignments[['date', 'time']].apply(lambda x: ' '.join(x), axis=1)
assignments["time"]=pd.to_datetime(assignments["time"])

In [9]:
assignments

,id,date,time,amp,type,prob,event_index,gamma_score
0,II.MSVF..BH,2009-11-01,2009-11-01 12:29:38.419900,0.000001,p,0.86,-1,-1.000000
1,II.MSVF..BH,2009-11-01,2009-11-01 16:03:19.149900,0.000001,p,0.91,31625,0.079182
2,II.MSVF..BH,2009-11-01,2009-11-01 20:23:03.249900,0.000001,p,0.97,12394,0.068525
3,II.MSVF..BH,2009-11-01,2009-11-01 20:59:34.149900,0.000001,p,0.70,-1,-1.000000
4,II.MSVF..BH,2009-11-01,2009-11-01 20:23:15.619900,0.000001,s,0.74,12394,0.052664
...,...,...,...,...,...,...,...,...
749544,Z1.VAVP..BH,2010-11-01,2010-11-01 15:59:39.440000,0.000001,p,0.93,32532,0.106648
749545,Z1.VAVP..BH,2010-11-01,2010-11-01 19:05:29.740000,0.000001,p,0.73,5656,0.110292
749546,Z1.VAVP..BH,2010-11-01,2010-11-01 19:06:43.610000,0.000001,s,0.86,5656,0.137580
749547,Z1.VAVP..BH,2010-11-01,2010-11-01 23:08:51.040000,0.000001,p,0.97,40530,0.149862
749548,Z1.VAVP..BH,2010-11-01,2010-11-01 23:09:49.640000,0.000001,s,0.97,40530,0.157528

In [12]:
# check in which 10 minutes the most picks are made, the 10 minutes window start at integer minutes such as 0min, 10min, 20min, 30min, 40min, 50min
# below is the code
start_time=pd.to_datetime("2009-11-01 00:00:00")
end_time=pd.to_datetime("2011-01-01 00:00:00")
time_range=pd.date_range(start=start_time,end=end_time,freq="10min")

frequency=[0]*(len(time_range)-1)
def check_frequency(row):
    # get row.time position in the frequency list
    time=row.time
    diff_to_start=time-time_range[0]
    index=int(diff_to_start.total_seconds()/600)
    frequency[index]+=1
assignments.apply(check_frequency,axis=1);

In [15]:
# get the top 10 time range and corresponding frequency
top_10_frequency=sorted(frequency,reverse=True)[:10]
top_10_time_range=[]
for i in range(10):
    index=frequency.index(top_10_frequency[i])
    top_10_time_range.append(time_range[index:index+2])

for i in range(10):
    print("top {} time range is {} to {}, frequency is {}".format(i+1,top_10_time_range[i][0],top_10_time_range[i][1],top_10_frequency[i]))

top 1 time range is 2010-07-24 10:30:00 to 2010-07-24 10:40:00, frequency is 171
top 2 time range is 2010-01-26 22:10:00 to 2010-01-26 22:20:00, frequency is 161
top 3 time range is 2010-09-15 13:40:00 to 2010-09-15 13:50:00, frequency is 159
top 4 time range is 2010-01-13 10:50:00 to 2010-01-13 11:00:00, frequency is 158
top 5 time range is 2009-12-07 17:20:00 to 2009-12-07 17:30:00, frequency is 156
top 6 time range is 2010-05-10 07:00:00 to 2010-05-10 07:10:00, frequency is 154
top 7 time range is 2010-10-22 12:10:00 to 2010-10-22 12:20:00, frequency is 153
top 8 time range is 2010-08-15 02:50:00 to 2010-08-15 03:00:00, frequency is 152
top 9 time range is 2010-02-07 23:20:00 to 2010-02-07 23:30:00, frequency is 150
top 10 time range is 2010-06-02 09:30:00 to 2010-06-02 09:40:00, frequency is 149