For the manual picks test, this notebook is designed to filter the catalog by 10 events.

In [1]:
import pandas as pd

In [2]:
assignment=pd.read_csv("/Users/ziyixi/Library/CloudStorage/OneDrive-MichiganStateUniversity/Paper/PhaseNetTF_myturn/PhaseNet-TF-Figures/phasenettf/data/catalog/manual_picks/manual_phase_picks.assignments.csv",sep=r"\s+")

In [3]:
assignment.head()

,event_id,id,timestamp,amp,type,prob,event_index,gamma_score
11_52111,YL.A01..BH,2009-12-02,01:14:41.317870,0.000001,p,1.0,1052,0.213809
11_52111,YL.A01..BH,2009-12-02,01:14:51.343700,0.000001,s,1.0,1052,0.213613
11_52111,YL.A02W..HH,2009-12-02,01:14:42.457750,0.000001,p,1.0,1052,0.196280
11_52111,YL.A02W..HH,2009-12-02,01:14:53.596650,0.000001,s,1.0,1052,0.202071
11_52111,YL.A03..BH,2009-12-02,01:14:43.547000,0.000001,p,1.0,1052,0.200115

In [4]:
catalog=pd.read_csv("/Users/ziyixi/Library/CloudStorage/OneDrive-MichiganStateUniversity/Paper/PhaseNetTF_myturn/PhaseNet-TF-Figures/phasenettf/data/catalog/manual_picks/manual_phase_picks.catalog.csv",sep=r"\s+")

In [5]:
catalog.head()

,time,x(km),y(km),z(km),magnitude,sigma_time,sigma_amp,cov_time_amp,event_index,gamma_score,longitude,latitude,depth(m)
0,2010-04-05T14:35:58.504,250.032136,-151.848926,211.315330,999,0.481940,0,0,31,25.000000,-175.605850,-20.355755,211315.329640
1,2010-03-01T08:48:42.766,-24.031792,164.752646,531.988000,999,0.990631,0,0,144,65.644039,-178.226265,-17.511445,531987.999991
2,2010-03-01T08:48:46.110,34.032555,145.021413,522.842526,999,2.915185,0,0,145,13.306131,-177.679249,-17.689561,522842.526026
3,2009-12-08T12:39:07.872,196.575884,-245.888647,208.602000,999,0.596766,0,0,65,25.000000,-176.107451,-21.210745,208602.000035
4,2010-04-17T01:37:08.645,63.474589,-133.066848,507.835920,999,1.038703,0,0,73,28.999885,-177.392737,-20.200993,507835.919993

In [11]:
# filter event_index with more than 10 assignment rows
event_index=assignment.groupby("event_index").count()
event_index=event_index[event_index["event_id"]>10]
event_index=set(event_index.index.tolist())

catalog=catalog[catalog["event_index"].isin(event_index)]

In [15]:
catalog.head()
catalog=catalog[["event_index","latitude","longitude","z(km)"]]
catalog.to_csv("/Users/ziyixi/Library/CloudStorage/OneDrive-MichiganStateUniversity/Paper/PhaseNetTF_myturn/PhaseNet-TF-Figures/phasenettf/data/catalog/manual_picks/manual_phase_picks.association_filtered.csv",index=False)